name: Terraform Deploy (Goshenignite)

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  TF_VERSION: "1.6.6"

jobs:
  bootstrap:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: AWS Auth (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ASSUME}}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Init (bootstrap-backend)
        working-directory: bootstrap-backend
        run: terraform init -input=false

      - name: Apply (bootstrap-backend)
        working-directory: bootstrap-backend
        run: terraform apply -input=false -auto-approve

  infra:
    runs-on: ubuntu-latest
    needs: bootstrap
    steps:
      - uses: actions/checkout@v4

      - name: AWS Auth (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ASSUME}}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Init (infra)
        working-directory: infra
        run: terraform init -input=false

      - name: Plan (infra)
        working-directory: infra
        run: terraform plan -input=false

      - name: Apply (infra)
        working-directory: infra
        run: terraform apply -input=false -auto-approve
